version: '3.7'
services:
  doxue-pc:
    #image: node:10.23.0-alpine3.11
    image: node-pm2-alpine:latest
    expose:
     - 3001
    ports:
      - "3001:3001"
    volumes:
     - /Users/Shared/workspace/huixue/doxue/web/frontend-pc:/www
    working_dir: /www
    command: pm2-runtime start npm --name "server" -i 0 -- run start

networks:
  default:
    external:
      name: servers
